github: ethers-io
custom: [ 'https://gitcoin.co/grants/13/ethersjs-complete-simple-and-tiny-2', 'https://www.buymeacoffee.com/ricmoo' ]
5097914914763a9b1ebd4b63efe3559be04d5d674 4https://github.com/ethereum/solidity/blob/develop/docs%2Fusing-the-compiler.rst
